name: Build APK (On Push)

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure your project's Node.js version matches

      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          rm sdk-tools.zip
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH"
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses || true
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Clear npm Cache
        run: npm cache clean --force

      - name: Remove node_modules and Reinstall Dependencies
        run: |
          rm -rf node_modules package-lock.json yarn.lock
          npm install  # Explicitly using npm instead of yarn

      - name: Install Missing Dependencies
        run: |
          npm install @react-navigation/native
          npm install react-native-screens react-native-safe-area-context
          npm install react-native-gesture-handler react-native-reanimated
          npm install react-native-vector-icons react-native-paper

      - name: Reset Metro Bundler Cache
        run: npx react-native start --reset-cache & sleep 5; exit 0

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
